### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by vbezruchkin** [Fulcanellii/Intelliants#1]
I would really appreciate the instructions to deploy it. What about admin panel details?

Thanks

**Comment by akulmambetov** [comment]
Прошу прощения, обновил файл readme12.08.2020, 19:33, "Vasily Bezruchkin" <notifications@github.com>:
I would really appreciate the instructions to deploy it. What about admin panel details?
Thanks

**Comment by vbezruchkin** [comment]
Мне не нравится вариант с дампом. Мы не можем это миграциями сделать?

P.S. Я развернул, но мне нужен "правильный" вариант. Зачем мне дамп? Если хочешь тестовые данные, сделай через миграции и сиды.

**Comment by akulmambetov** [comment]
Можно через миграции, они присутствуют12.08.2020, 22:33, "Vasily Bezruchkin" <notifications@github.com>:
Мне не нравится вариант с дампом. Мы не можем это миграциями сделать?
P.S. Я развернул, но мне нужен "правильный" вариант. Зачем мне дамп? Если хочешь тестовые данные, сделай через миграции и сиды.
